export default [
    'Social Butterfly',
    'Ambitious',
    'Confident',
    'Party Animal',
    'Problem Solver', 
    'Einstein',
    'Bookworm',
    'Analytical',
    'Puzzle Solver',
    'Artsy Fartsy',
    'Photographer',
    'Music Lover',
    'Patron of the Arts',
    'Trend Setter',
    'Shy',
    'Wallflower',
    'Gentle Giant',
    'Awkward Turtle',
    'Adventurous',
    'World Traveler',
    'Health Nut',
    'Athletic',
    'Homebody',
    'Nerdy',
    'Stoner',
    'Binge Watcher',
    'Wine Connoisseur',
    'Early Bird',
    'Night Owl',
    'Foodie'
]