export default [
    "happy",
    "sad",
    "chill",
    "Health Nut",
    "Patron of the Arts",
    "Sport Enthusist",
    "Party ANIMAL",
    "Stoner",
    "Cats!!!",
    "Dogs!!!",
    "Dogs || Cats",
    "Theater Kid",
    "Couch Potato",
    "Outdoorsy",
    "Socially Conscious",
    "Raver",
    "Religious",
    "Agnostic",
    "Atheist",
    "Conservative",
    "Liberal",
    "Dominant",
    "Creative",
    "Analytical",
    "Loyal",
    "Thoughtful",
    "Charitable",
    "Outcast",
    "Edgy",
    "Outgoing",
    "Adventerous",
    "Shy",
    "Confident",
    "Athletic",
    "Not So Athletic",
    "Morning Person",
    "Night Owl",
    "Goal-Driven",
    "Que Sera Sera",
    "Family-Oriented",
    "Nerdy",
    "Not Nerdy",
    "Passionate",
    "Sensitive",
    "Empathetic",
    "Penny Pincher",
    "Big Spender",
    "Dancefloor Killer",
    "Wild and Rowdy",
    "Calm and Patient"
]