insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('earrigo0', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','earrigo0@smugmug.com',  'Arrigo', 'Em', 19900101, 90023, 1, 2, 'Innovative systemic hub', 178, 100, 99, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('wrainer1', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','wrainer1@wired.com',  'Rainer', 'Wendye', 19900101, 90023, 1, 2, 'Cross-group explicit frame', 3, 98, 26, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('mcejka2', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','mcejka2@photobucket.com',  'Cejka', 'Morlee', 19910101, 90024, 1, 1, 'Upgradable hybrid attitude', 80, 74, 42, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('soffner3', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','soffner3@mtv.com',  'Offner', 'Shaughn', 19910101, 90032, 1, 2, 'Realigned coherent strategy', 78, 89, 49, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('sallflatt4', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','sallflatt4@theglobeandmail.com',  'Allflatt', 'Staford', 19830101, 90034, 1, 1, 'Fully-configurable secondary open architecture', 54, 91, 24, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('afenty5', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','afenty5@usgs.gov',  'Fenty', 'Ariana', 19800101, 90032, 1, 2, 'Open-source asynchronous ability', 314, 75, 42, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('lstanier6', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','lstanier6@amazon.com',  'Stanier', 'Lombard', 19820101, 90052, 1, 7, 'Managed intermediate hierarchy', 124, 80, 21, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('cgiblett7', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','cgiblett7@icq.com',  'Giblett', 'Cchaddie', 19910101, 90047, 1, 5, 'Customer-focused 24/7 capacity', 432, 73, 8, 9, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('rdoulden8', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','rdoulden8@cdbaby.com',  'Doulden', 'Rutger', 19920101, 90211, 1, 2, 'Reactive uniform circuit', 66, 72, 31, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('tschuler9', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','tschuler9@businesswire.com',  'Schuler', 'Tricia', 19900101, 90201, 1, 4, 'Optimized context-sensitive local area network', 263, 7, 24, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('jaggeta', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','jaggeta@earthlink.net',  'Agget', 'Julee', 19780101, 90201, 1, 1, 'Versatile asymmetric encoding', 150, 83, 66, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('froizinb', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','froizinb@reuters.com',  'Roizin', 'Fran', 19790101, 90212, 1, 2, 'Profit-focused homogeneous functionalities', 28, 87, 18, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('dbegginc', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','dbegginc@ow.ly',  'Beggin', 'Daphna', 19810101, 90302, 1, 3, 'Persistent zero tolerance attitude', 176, 80, 69, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('bmcettigend', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','bmcettigend@pbs.org',  'McEttigen', 'Bernadina', 19780101, 90310, 1, 2, 'Re-engineered zero administration help-desk', 220, 34, 32, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('lpaolonee', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','lpaolonee@hugedomains.com',  'Paolone', 'Lynnette', 19840101, 90397, 1, 6, 'Organized multimedia moratorium', 386, 58, 22, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('cpressdeef', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','cpressdeef@google.fr',  'Pressdee', 'Cherrita', 19880101, 90408, 1, 2, 'Multi-tiered well-modulated intranet', 457, 78, 10, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('edelgardog', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','edelgardog@samsung.com',  'Delgardo', 'Elena', 19880101, 90410, 1, 1, 'Implemented multi-state portal', 98, 74, 11, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('svanbruggenh', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','svanbruggenh@sogou.com',  'Van Bruggen', 'Skippie', 19900101, 90508, 1, 2, 'Digitized encompassing Graphical User Interface', 319, 94, 10, 9, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('mlatani','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'mlatani@sohu.com',  'Latan', 'Melisenda', 19890101, 90020, 1, 2, 'Mandatory multi-tasking emulation', 41, 53, 7, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('eserrisj', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','eserrisj@psu.edu',  'Serris', 'Eleni', 19930101, 9068, 1, 4, 'Operative web-enabled neural-net', 466, 56, 29, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('ncelandk', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','ncelandk@prnewswire.com',  'Celand', 'Niven', 19920101, 90610, 1, 5, 'Horizontal hybrid benchmark', 355, 62, 68, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('kcallaghanl', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','kcallaghanl@squarespace.com',  'Callaghan', 'Kristin', 19900101, 90622, 1, 1, 'Integrated 24/7 adapter', 488, 50, 40, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('ehadlingtonm', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','ehadlingtonm@cdbaby.com',  'Hadlington', 'Engelbert', 19910101, 90608, 1, 2, 'Mandatory mobile hub', 45, 42, 16, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('bmattinsonn', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','bmattinsonn@vimeo.com',  'Mattinson', 'Blair', 19940101, 90011, 1, 7, 'Total non-volatile website', 374, 90, 54, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('plillyo', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','plillyo@tripadvisor.com',  'Lilly', 'Pennie', 19950101, 90019, 1, 2, 'Progressive responsive matrix', 258, 240, 30, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('ajendruschp', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','ajendruschp@census.gov',  'Jendrusch', 'Alanah', 19920101, 90025, 1, 2, 'Polarised non-volatile monitoring', 458, 97, 16, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('lzorzinq', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','lzorzinq@utexas.edu',  'Zorzin', 'Lindy', 19940101, 90026, 1, 2, 'Streamlined regional installation', 219, 90, 13, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('rtabourinr', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','rtabourinr@trellian.com',  'Tabourin', 'Rivkah', 19920101, 90025, 1, 3, 'Optimized intangible initiative', 243, 23, 10, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('lboyalls', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','lboyalls@tmall.com',  'Boyall', 'Loralie', 19950101, 90027, 1, 1, 'User-centric asynchronous info-mediaries', 187, 96, 83, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('cmckinnont', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','cmckinnont@ask.com',  'McKinnon', 'Claretta', 19790101, 90059, 1, 2, 'Realigned client-server time-frame', 307, 61, 23, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('nrandleu', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','nrandleu@cpanel.net',  'Randle', 'Norene', 19840101, 90060, 1, 2, 'Pre-emptive foreground hardware', 345, 100, 45, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('molyetv', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','molyetv@berkeley.edu',  'Olyet', 'Meg', 19900101, 90061, 2, 1, 'Extended multi-tasking frame', 480, 150, 27, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('lwhiskinw', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','lwhiskinw@ehow.com',  'Whiskin', 'Leeland', 19800101, 90064, 2, 5, 'Team-oriented dynamic knowledge base', 216, 175, 35, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('sjakuboviczx', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','sjakuboviczx@soundcloud.com',  'Jakubovicz', 'Sherline', 19790101, 90089, 2, 4, 'Stand-alone composite intranet', 92, 95, 34, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('ssawyery', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','ssawyery@seesaa.net',  'Sawyer', 'Sheffield', 19930101, 90095, 2, 7, 'Advanced grid-enabled contingency', 369, 69, 12, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('rmuggeridgez','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'rmuggeridgez@ovh.net',  'Muggeridge', 'Rowney', 19950101, 90213, 2, 1, 'Devolved 24/7 forecast', 95, 73, 74, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('agaveltone10', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','agaveltone10@goodreads.com',  'Gaveltone', 'Ailyn', 19960101, 90213, 2, 1, 'Future-proofed bi-directional matrices', 73, 34, 34, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('tbarnshaw11', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','tbarnshaw11@php.net',  'Barnshaw', 'Thorstein', 19930101, 90239, 2, 2, 'Customizable systematic analyzer', 282, 552, 69, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('tblackeby12', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','tblackeby12@storify.com',  'Blackeby', 'Tod', 19900101, 90231, 2, 2, 'Exclusive zero defect artificial intelligence', 234, 567, 81, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('ckield13', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','ckield13@qq.com',  'Kield', 'Collete', 19980101, 90211, 2, 1, 'Proactive client-server internet solution', 485, 174, 29, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('bfoottit14', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','bfoottit14@stumbleupon.com',  'Foottit', 'Bancroft', 19920101, 90277, 2, 1, 'Fundamental fresh-thinking conglomeration', 213, 850, 85, 10, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('gfluger15', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','gfluger15@yellowbook.com',  'Fluger', 'Galvan', 19910101, 90278, 2, 3, 'Reverse-engineered bi-directional migration', 418, 510, 51, 10, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('abusen16', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','abusen16@seesaa.net',  'Busen', 'Alis', 19930101, 90294, 2, 2, 'Cloned tangible budgetary management', 100, 492, 82, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('cmaha17', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','cmaha17@com.com',  'Maha', 'Conny', 19930909, 90312, 2, 1, 'Optional homogeneous matrix', 127, 267, 89, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('hsharrocks18', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','hsharrocks18@taobao.com',  'Sharrocks', 'Hector', 19900101, 90409, 2, 1, 'User-friendly systemic productivity', 77, 700, 100, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('daviss19', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','daviss19@businesswire.com',  'Aviss', 'Dinnie', 19890101, 90411, 2, 3, 'Diverse clear-thinking encryption', 298, 104, 13, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('mbonellie1a', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','mbonellie1a@virginia.edu',  'Bonellie', 'Minne', 19980101, 9052, 2, 1, 'Realigned didactic workforce', 267, 124, 31, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('ckilbane1b', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','ckilbane1b@skyrock.com',  'Kilbane', 'Callida', 19980101, 90510, 2, 1, 'Ergonomic well-modulated throughput', 363, 432, 72, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('bgilbee1c', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','bgilbee1c@typepad.com',  'Gilbee', 'Bret', 19970101, 91124, 2, 2, 'User-centric incremental software', 278, 114, 38, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('cmashal1d', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','cmashal1d@flickr.com',  'Mashal', 'Cathe', 19960101, 91126, 2, 2, 'Universal high-level forecast', 477, 385, 77, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('vpady1e', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','vpady1e@army.mil',  'Pady', 'Vivyan', 19930101, 91199, 2, 1, 'Decentralized bandwidth-monitored website', 100, 546, 78, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('sbellison1f', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','sbellison1f@google.nl',  'Bellison', 'Shayla', 19930101, 91203, 2, 3, 'Polarised bifurcated hierarchy', 219, 80, 20, 4,true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('fpostlethwaite1g', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','fpostlethwaite1g@edublogs.org',  'Postlethwaite', 'Frants', 19900101, 91209, 2, 7, 'Multi-tiered asymmetric benchmark', 480, 230, 23, 10, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('egaunter1h', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','egaunter1h@scribd.com',  'Gaunter', 'Evvy', 19830101, 91126, 2, 2, 'Ameliorated dedicated circuit', 177, 115, 23, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('jspark1i', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','jspark1i@devhub.com',  'Spark', 'Jena', 19840101, 91324, 2, 1, 'Expanded transitional synergy', 349, 882, 98, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('thildrew1j', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','thildrew1j@github.io',  'Hildrew', 'Timothy', 19920101, 9135, 2, 2, 'Multi-channelled object-oriented Graphic Interface', 309, 256, 64, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('jjeune1k', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','jjeune1k@google.de',  'Jeune', 'Jamaal', 19890101, 91329, 2, 1, 'Universal composite flexibility', 239, 54, 9, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('dmandell1l', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','dmandell1l@technorati.com',  'Mandell', 'Dwain', 19910101, 91358, 2, 1, 'Down-sized reciprocal functionalities', 167, 300, 50, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('awhittall1m', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','awhittall1m@hugedomains.com',  'Whittall', 'Arlina', 19870101, 91360, 2, 1, 'Virtual hybrid instruction set', 106, 590, 59, 10, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('kbrickhill1n','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'kbrickhill1n@xing.com',  'Brickhill', 'Kristoffer', 19880101, 91359, 2, 2, 'De-engineered analyzing product', 206, 405, 45, 9, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('tlaise1o', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','tlaise1o@shutterfly.com',  'Laise', 'Thibaud', 19780101, 91360, 2, 4, 'Enhanced uniform capability', 483, 245, 35, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('bmaydwell1p','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'bmaydwell1p@goo.gl',  'Maydwell', 'Brena', 19690101, 91601, 2, 1, 'Multi-tiered needs-based array', 89, 270, 45, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('adriffill1q','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'adriffill1q@networkadvertising.org',  'Driffill', 'Andree', 19750101, 91605, 2, 1, 'Automated 4th generation interface', 95, 290, 58, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('jabbet1r', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','jabbet1r@istockphoto.com',  'Abbet', 'Jefferson', 19790101, 91609, 2, 1, 'Re-engineered intangible portal', 52, 252, 28, 9, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('hhanna1s', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','hhanna1s@youtube.com',  'Hanna', 'Harriot', 19890101, 91608, 1, 4, 'Organic local functionalities', 71, 640, 80, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('tgrimestone1t', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','tgrimestone1t@admin.ch',  'Grimestone', 'Teador', 19960101, 91608, 2, 3, 'Expanded systemic challenge', 497, 435, 87, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('bbevans1u', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','bbevans1u@yellowbook.com',  'Bevans', 'Bendicty', 19780101, 91608, 3, 3, 'Secured well-modulated portal', 298, 212, 53, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('eperutto1v', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','eperutto1v@dagondesign.com',  'Perutto', 'Ealasaid', 19780101, 92037, 2, 2, 'Front-line contextually-based info-mediaries', 70, 160, 32, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('akingswood1w', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','akingswood1w@stanford.edu',  'Kingswood', 'Alwin', 19880101, 92049, 1, 1, 'Enhanced impactful matrix', 83, 330, 33, 10, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('gyannikov1x', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','gyannikov1x@buzzfeed.com',  'Yannikov', 'Gilles', 19930101, 92039, 3, 5, 'Expanded modular ability', 297, 420, 60, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('iwolfarth1y', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','iwolfarth1y@globo.com',  'Wolfarth', 'Isidoro', 19990101, 90014, 3, 3, 'Public-key bandwidth-monitored time-frame', 87, 344, 86, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('ndonahue1z', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','ndonahue1z@abc.net.au',  'Donahue', 'Nissie', 19870101, 90028, 3, 4, 'Persistent system-worthy knowledge base', 166, 837, 93, 9, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('crasp20', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','crasp20@lulu.com',  'Rasp', 'Constance', 19880101, 90051, 3, 7, 'Horizontal asymmetric frame', 458, 180, 45, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('tbatho21', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','tbatho21@sina.com.cn',  'Batho', 'Templeton', 19880101, 90060, 3, 7, 'Ergonomic intangible hardware', 145, 194, 97, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('dduffield22', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','dduffield22@freewebs.com',  'Duffield', 'Dale', 19910101, 90066, 3, 7, 'Quality-focused incremental intranet', 484, 52, 52, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('vsemken23', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','vsemken23@cpanel.net',  'Semken', 'Vittoria', 19900101, 90070, 3, 3, 'Reduced background firmware', 3, 595, 85, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('dwheelhouse24', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','dwheelhouse24@noaa.gov',  'Wheelhouse', 'Dreddy', 19930101, 90068, 3, 3, 'Self-enabling explicit website', 197, 648, 81, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('tseamon25', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','tseamon25@admin.ch',  'Seamon', 'Toiboid', 19940101, 90069, 1, 2, 'Mandatory maximized open system', 86, 567, 63, 9, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('mburgum26','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'mburgum26@shop-pro.jp',  'Burgum', 'Mareah', 19920101, 90071, 2, 1, 'Synchronised neutral focus group', 110, 280, 40, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('scaveau27', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','scaveau27@archive.org',  'Caveau', 'Saundra', 19910101, 90071, 1, 2, 'Progressive uniform array', 410, 282, 94, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('lkalberer28', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','lkalberer28@arstechnica.com',  'Kalberer', 'Lynsey', 19930101, 2, 2, 'Synergistic even-keeled success', 345, 136, 17, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('wjurisch29', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','wjurisch29@bbb.org',  'Jurisch', 'Wendy', 198830101, 90034, 3, 5, 'Managed incremental initiative', 406, 355, 71, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('fabbe2a', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','fabbe2a@cyberchimps.com',  'Abbe', 'Frederick', 19780101, 90034, 1, 2, 'Fully-configurable fault-tolerant concept', 440, 168, 84, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('tflanner2b', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','tflanner2b@a8.net',  'Flanner', 'Terrijo', 19880101, 91504, 3, 6, 'Digitized fresh-thinking synergy', 462, 90, 90, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('sgodball2c', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','sgodball2c@squarespace.com',  'Godball', 'Sissie', 19890101, 91504, 3, 7, 'Cross-group executive flexibility', 273, 450, 90, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('afagence2d','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'afagence2d@i2i.jp',  'Fagence', 'Abe', 19900101, 92844, 3, 6, 'Optional content-based middleware', 475, 136, 34, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('lfinders2e','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'lfinders2e@pcworld.com',  'Finders', 'Letizia', 19940101, 92844, 3, 3, 'Operative client-server intranet', 477, 350, 35, 10, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('iharkins2f','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'iharkins2f@blinklist.com',  'Harkins', 'Igor', 19700101, 92841, 3, 3, 'Managed solution-oriented hierarchy', 125, 38, 38, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('mlenox2g','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'mlenox2g@prnewswire.com',  'Lenox', 'Meryl', 19780101, 90069, 3, 7, 'Public-key upward-trending ability', 121, 96, 32, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('acohn2h', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','acohn2h@forbes.com',  'Cohn', 'Alfie', 19870101, 90052, 3, 7, 'Customizable upward-trending application', 93, 31, 31, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('icappleman2i','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'icappleman2i@purevolume.com',  'Cappleman', 'Imojean', 19880101, 90052, 3, 3, 'Upgradable bifurcated customer loyalty', 265, 35, 7, 5, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('dfinnie2j','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'dfinnie2j@vistaprint.com',  'Finnie', 'Darn', 19900101, 90070, 1, 2, 'Synchronised client-driven application', 48, 63, 21, 3, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('bmartensen2k','6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'bmartensen2k@geocities.com',  'Martensen', 'Blanche', 19980101, 90071, 2, 1, 'Proactive tertiary capacity', 363, 16, 4, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('dfayter2l', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','dfayter2l@virginia.edu',  'Fayter', 'Deanna', 19840101, 90072, 3, 6, 'Optimized directional adapter', 85, 56, 7, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('aschimaschke2m', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','aschimaschke2m@dagondesign.com',  'Schimaschke', 'Alastair', 19890101, 90020, 3, 3, 'Enterprise-wide real-time functionalities', 432, 330, 33, 10, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('jstoeck2n', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','jstoeck2n@eepurl.com',  'Stoeck', 'Jamie', 19860101, 90022, 3, 3, 'Customizable demand-driven workforce', 190, 16, 8, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('haxtell2o', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','haxtell2o@theglobeandmail.com',  'Axtell', 'Holli', 19920101, 90041, 3, 4, 'Polarised foreground instruction set', 172, 256, 64, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('rwedon2p', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','rwedon2p@mit.edu',  'Wedon', 'Roslyn', 19920101, 90232, 1, 1, 'Proactive object-oriented flexibility', 9, 228, 57, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('svallentine2q', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','svallentine2q@surveymonkey.com',  'Vallentine', 'Staci', 19980101, 90232, 2, 1, 'Multi-tiered fresh-thinking circuit', 403, 44, 44, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('rcosterd2r', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','rcosterd2r@china.com.cn',  'Costerd', 'Rodrique', 19920101, 90255, 3, 3, 'Self-enabling value-added algorithm', 6, 450, 50, 9, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerranking, totalattractiveness, totalnumofratings, averageattractiveness, signupcomplete) values ('hello123', '6c12a3cd28b6e5730535c2d926e619137f30f5cc','test@test.com',  'Tester', 'Boop', 19920101, 90255, 1, 2, 'Self-enabling value-added algorithm', 6, 450, 50, 9, true);


insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (7, 25, 100, 20, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (6, 21, 34, 90, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (10, 22, 0, 100, 0);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (8, 16, 1, 4, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (2, 20, 3, 90, 0);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (3, 21, 150, 20, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (4, 23, 26, 29, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (1, 16, 29, 28, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (4, 14, 35, 21, 0);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (7, 15, 14, 34, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (12, 16, 16, 42, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (13, 22, 12, 89, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (8, 19, 90, 12, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (12, 16, 45, 2, 1);
insert into match (user1_id, user2_id, approvedcount, rejectedcount, activevoting) values (4, 25, 23, 22, 1);

insert into outcomes (userid, matchid, decision) values (24, 2, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 4, 'approved');
insert into outcomes (userid, matchid, decision) values (8, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (1, 6, 'approved');
insert into outcomes (userid, matchid, decision) values (15, 10, 'approved');
insert into outcomes (userid, matchid, decision) values (12, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (2, 2, 'approved');
insert into outcomes (userid, matchid, decision) values (20, 11, 'approved');
insert into outcomes (userid, matchid, decision) values (7, 1, 'approved');
insert into outcomes (userid, matchid, decision) values (16, 8, 'approved');
insert into outcomes (userid, matchid, decision) values (8, 6, 'approved');
insert into outcomes (userid, matchid, decision) values (17, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (13, 9, 'approved');
insert into outcomes (userid, matchid, decision) values (1, 7, 'approved');
insert into outcomes (userid, matchid, decision) values (15, 14, 'approved');
insert into outcomes (userid, matchid, decision) values (17, 14, 'approved');
insert into outcomes (userid, matchid, decision) values (18, 12, 'approved');
insert into outcomes (userid, matchid, decision) values (4, 5, 'approved');
insert into outcomes (userid, matchid, decision) values (11, 4, 'approved');
insert into outcomes (userid, matchid, decision) values (11, 11, 'approved');
insert into outcomes (userid, matchid, decision) values (20, 10, 'approved');
insert into outcomes (userid, matchid, decision) values (22, 13, 'approved');
insert into outcomes (userid, matchid, decision) values (1, 10, 'approved');
insert into outcomes (userid, matchid, decision) values (17, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (25, 9, 'approved');
insert into outcomes (userid, matchid, decision) values (8, 2, 'approved');
insert into outcomes (userid, matchid, decision) values (15, 7, 'approved');
insert into outcomes (userid, matchid, decision) values (25, 5, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 14, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 12, 'approved');
insert into outcomes (userid, matchid, decision) values (20, 13, 'approved');
insert into outcomes (userid, matchid, decision) values (7, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 4, 'approved');
insert into outcomes (userid, matchid, decision) values (9, 13, 'rejected');
insert into outcomes (userid, matchid, decision) values (18, 10, 'rejected');
insert into outcomes (userid, matchid, decision) values (5, 4, 'rejected');
insert into outcomes (userid, matchid, decision) values (25, 5, 'rejected');
insert into outcomes (userid, matchid, decision) values (12, 12, 'rejected');
insert into outcomes (userid, matchid, decision) values (24, 13, 'rejected');
insert into outcomes (userid, matchid, decision) values (5, 14, 'rejected');
insert into outcomes (userid, matchid, decision) values (17, 11, 'rejected');
insert into outcomes (userid, matchid, decision) values (22, 14, 'rejected');
insert into outcomes (userid, matchid, decision) values (2, 8, 'rejected');
insert into outcomes (userid, matchid, decision) values (13, 7, 'rejected');
insert into outcomes (userid, matchid, decision) values (17, 6, 'rejected');
insert into outcomes (userid, matchid, decision) values (25, 13, 'rejected');
insert into outcomes (userid, matchid, decision) values (20, 14, 'rejected');
insert into outcomes (userid, matchid, decision) values (19, 5, 'rejected');
insert into outcomes (userid, matchid, decision) values (10, 15, 'rejected');

insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (1, 1, 0, 7, 25, null);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (2, 1, 0, 6, null, 21);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (3, 1, 0, 10, null, 22);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (4, 1, 0, 8, 16, null);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (5, 1, 0, 20, null, null);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (6, 0, 1, null, null, null);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (7, 0, 1, null, null, null);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (8, 0, 1, null, null, null);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (9, 0, 1, null, null, null);
insert into stagetwo (matchid, issuccessful, active, firstaccept, secondaccept, firstrejection) values (10, 0, 1, null, null, null);

insert into tags (tag) values ('Social Butterfly');
insert into tags (tag) values ('Ambitious');
insert into tags (tag) values ('Confident');
insert into tags (tag) values ('Party Animal');
insert into tags(tag) values ('Problem Solver');
insert into tags(tag) values ('Einstein');
insert into tags(tag) values ('Bookworm');
insert into tags(tag) values ('Analytical');
insert into tags(tag) values ('Puzzle Solver');
insert into tags(tag) values ('Artsy Fartsy');
insert into tags(tag) values ('Photographer');
insert into tags(tag) values ('Music Lover');
insert into tags(tag) values ('Patron of the Arts');
insert into tags(tag) values ('Trend Setter');
insert into tags(tag) values ('Shy');
insert into tags(tag) values ('Wallflower');
insert into tags(tag) values ('Gentle Giant');
insert into tags(tag) values ('Awkward Turtle');
insert into tags(tag) values ('Adventurous');
insert into tags(tag) values ('World Traveler');
insert into tags(tag) values ('Health Nut');
insert into tags(tag) values ('Athletic');
insert into tags(tag) values ('Homebody');
insert into tags(tag) values ('Nerdy');
insert into tags(tag) values ('Stoner');
insert into tags(tag) values ('Binge Watcher');
insert into tags(tag) values ('Wine Connoisseur');
insert into tags(tag) values ('Early Bird');
insert into tags(tag) values ('Night Owl');
insert into tags(tag) values ('Foodie');

insert into users_tags (tagid, userid, type) values (2, 1, 0);
insert into users_tags (tagid, userid, type) values (3, 1, 0);
insert into users_tags (tagid, userid, type) values (1, 1, 0);
insert into users_tags (tagid, userid, type) values (1, 1, 1);
insert into users_tags (tagid, userid, type) values (2, 1, 1);
insert into users_tags (tagid, userid, type) values (3, 1, 1);
insert into users_tags (tagid, userid, type) values (1, 2, 0);
insert into users_tags (tagid, userid, type) values (2, 2, 0);
insert into users_tags (tagid, userid, type) values (3, 2, 0);
insert into users_tags (tagid, userid, type) values (1, 2, 1);
insert into users_tags (tagid, userid, type) values (2, 2, 1);
insert into users_tags (tagid, userid, type) values (3, 2, 1);
insert into users_tags (tagid, userid, type) values (28, 3, 0);
insert into users_tags (tagid, userid, type) values (21, 3, 0);
insert into users_tags (tagid, userid, type) values (12, 3, 0);
insert into users_tags (tagid, userid, type) values (15, 3, 1);
insert into users_tags (tagid, userid, type) values (22, 3, 1);
insert into users_tags (tagid, userid, type) values (11, 3, 1);
insert into users_tags (tagid, userid, type) values (21, 4, 0);
insert into users_tags (tagid, userid, type) values (22, 4, 0);
insert into users_tags (tagid, userid, type) values (28, 4, 0);
insert into users_tags (tagid, userid, type) values (28, 4, 1);
insert into users_tags (tagid, userid, type) values (1, 4, 1);
insert into users_tags (tagid, userid, type) values (3, 4, 1);
insert into users_tags (tagid, userid, type) values (5, 5, 0);
insert into users_tags (tagid, userid, type) values (1, 5, 0);
insert into users_tags (tagid, userid, type) values (8, 5, 0);
insert into users_tags (tagid, userid, type) values (2, 5, 1);
insert into users_tags (tagid, userid, type) values (21, 5, 1);
insert into users_tags (tagid, userid, type) values (20, 5, 1);
insert into users_tags (tagid, userid, type) values (3, 6, 0);
insert into users_tags (tagid, userid, type) values (1, 6, 0);
insert into users_tags (tagid, userid, type) values (28, 6, 0);
insert into users_tags (tagid, userid, type) values (22, 6, 1);
insert into users_tags (tagid, userid, type) values (21, 6, 1);
insert into users_tags (tagid, userid, type) values (20, 6, 1);
insert into users_tags (tagid, userid, type) values (20, 7, 0);
insert into users_tags (tagid, userid, type) values (26, 7, 0);
insert into users_tags (tagid, userid, type) values (9, 7, 0);
insert into users_tags (tagid, userid, type) values (6, 7, 1);
insert into users_tags (tagid, userid, type) values (13, 7, 1);
insert into users_tags (tagid, userid, type) values (5, 7, 1);
insert into users_tags (tagid, userid, type) values (24, 8, 0);
insert into users_tags (tagid, userid, type) values (18, 8, 0);
insert into users_tags (tagid, userid, type) values (14, 8, 0);
insert into users_tags (tagid, userid, type) values (23, 8, 1);
insert into users_tags (tagid, userid, type) values (21, 8, 1);
insert into users_tags (tagid, userid, type) values (25, 8, 1);
insert into users_tags (tagid, userid, type) values (27, 8, 1);
insert into users_tags (tagid, userid, type) values (1, 9, 0);
insert into users_tags (tagid, userid, type) values (2, 9, 0);
insert into users_tags (tagid, userid, type) values (22, 9, 0);
insert into users_tags (tagid, userid, type) values (15, 9, 1);
insert into users_tags (tagid, userid, type) values (7, 9, 1);
insert into users_tags (tagid, userid, type) values (22, 9, 1);
insert into users_tags (tagid, userid, type) values (4, 10, 0);
insert into users_tags (tagid, userid, type) values (24, 10, 0);
insert into users_tags (tagid, userid, type) values (10, 10, 0);
insert into users_tags (tagid, userid, type) values (4, 10, 1);
insert into users_tags (tagid, userid, type) values (26, 10, 1);
insert into users_tags (tagid, userid, type) values (30, 10, 1);
insert into users_tags (tagid, userid, type) values (30, 11, 0);
insert into users_tags (tagid, userid, type) values (27, 11, 0);
insert into users_tags (tagid, userid, type) values (17, 11, 0);
insert into users_tags (tagid, userid, type) values (27, 11, 1);
insert into users_tags (tagid, userid, type) values (11, 11, 1);
insert into users_tags (tagid, userid, type) values (10, 11, 1);
insert into users_tags (tagid, userid, type) values (9, 12, 0);
insert into users_tags (tagid, userid, type) values (13, 12, 0);
insert into users_tags (tagid, userid, type) values (26, 12, 0);
insert into users_tags (tagid, userid, type) values (19, 12, 1);
insert into users_tags (tagid, userid, type) values (27, 12, 1);
insert into users_tags (tagid, userid, type) values (29, 12, 1);
insert into users_tags (tagid, userid, type) values (27, 13, 0);
insert into users_tags (tagid, userid, type) values (6, 13, 0);
insert into users_tags (tagid, userid, type) values (3, 13, 0);
insert into users_tags (tagid, userid, type) values (8, 13, 1);
insert into users_tags (tagid, userid, type) values (12, 13, 1);
insert into users_tags (tagid, userid, type) values (6, 13, 1);
insert into users_tags (tagid, userid, type) values (3, 14, 0);
insert into users_tags (tagid, userid, type) values (14, 14, 0);
insert into users_tags (tagid, userid, type) values (26, 14, 0);
insert into users_tags (tagid, userid, type) values (16, 14, 1);
insert into users_tags (tagid, userid, type) values (10, 14, 1);
insert into users_tags (tagid, userid, type) values (19, 14, 1);
insert into users_tags (tagid, userid, type) values (2, 15, 0);
insert into users_tags (tagid, userid, type) values (14, 15, 0);
insert into users_tags (tagid, userid, type) values (15, 15, 0);
insert into users_tags (tagid, userid, type) values (4, 15, 1);
insert into users_tags (tagid, userid, type) values (22, 15, 1);
insert into users_tags (tagid, userid, type) values (28, 15, 1);
insert into users_tags (tagid, userid, type) values (23, 16, 0);
insert into users_tags (tagid, userid, type) values (1, 16, 0);
insert into users_tags (tagid, userid, type) values (28, 16, 0);
insert into users_tags (tagid, userid, type) values (22, 16, 1);
insert into users_tags (tagid, userid, type) values (8, 16, 1);
insert into users_tags (tagid, userid, type) values (11, 16, 1);
insert into users_tags (tagid, userid, type) values (9, 17, 0);
insert into users_tags (tagid, userid, type) values (10, 17, 0);
insert into users_tags (tagid, userid, type) values (6, 17, 0);
insert into users_tags (tagid, userid, type) values (20, 17, 1);
insert into users_tags (tagid, userid, type) values (14, 17, 1);
insert into users_tags (tagid, userid, type) values (8, 17, 1);
insert into users_tags (tagid, userid, type) values (23, 18, 0);
insert into users_tags (tagid, userid, type) values (21, 18, 0);
insert into users_tags (tagid, userid, type) values (11, 18, 0);
insert into users_tags (tagid, userid, type) values (20, 18, 1);
insert into users_tags (tagid, userid, type) values (29, 18, 1);
insert into users_tags (tagid, userid, type) values (9, 18, 1);
insert into users_tags (tagid, userid, type) values (2, 19, 0);
insert into users_tags (tagid, userid, type) values (3, 19, 0);
insert into users_tags (tagid, userid, type) values (10, 19, 0);
insert into users_tags (tagid, userid, type) values (10, 19, 1);
insert into users_tags (tagid, userid, type) values (12, 19, 1);
insert into users_tags (tagid, userid, type) values (13, 19, 1);
insert into users_tags (tagid, userid, type) values (8, 20, 0);
insert into users_tags (tagid, userid, type) values (28, 20, 0);
insert into users_tags (tagid, userid, type) values (21, 20, 0);
insert into users_tags (tagid, userid, type) values (5, 20, 1);
insert into users_tags (tagid, userid, type) values (8, 20, 1);
insert into users_tags (tagid, userid, type) values (3, 20, 1);
insert into users_tags (tagid, userid, type) values (15, 21, 0);
insert into users_tags (tagid, userid, type) values (1, 21, 0);
insert into users_tags (tagid, userid, type) values (28, 21, 0);
insert into users_tags (tagid, userid, type) values (27, 21, 1);
insert into users_tags (tagid, userid, type) values (17, 21, 1);
insert into users_tags (tagid, userid, type) values (4, 21, 1);
insert into users_tags (tagid, userid, type) values (1, 22, 0);
insert into users_tags (tagid, userid, type) values (25, 22, 0);
insert into users_tags (tagid, userid, type) values (11, 22, 0);
insert into users_tags (tagid, userid, type) values (2, 22, 1);
insert into users_tags (tagid, userid, type) values (26, 22, 1);
insert into users_tags (tagid, userid, type) values (15, 22, 1);
insert into users_tags (tagid, userid, type) values (2, 23, 0);
insert into users_tags (tagid, userid, type) values (16, 23, 0);
insert into users_tags (tagid, userid, type) values (10, 23, 0);
insert into users_tags (tagid, userid, type) values (25, 23, 1);
insert into users_tags (tagid, userid, type) values (18, 23, 1);
insert into users_tags (tagid, userid, type) values (24, 23, 1);
insert into users_tags (tagid, userid, type) values (28, 24, 0);
insert into users_tags (tagid, userid, type) values (19, 24, 0);
insert into users_tags (tagid, userid, type) values (27, 24, 0);
insert into users_tags (tagid, userid, type) values (18, 24, 1);
insert into users_tags (tagid, userid, type) values (20, 24, 1);
insert into users_tags (tagid, userid, type) values (3, 24, 1);
insert into users_tags (tagid, userid, type) values (13, 25, 0);
insert into users_tags (tagid, userid, type) values (2, 25, 0);
insert into users_tags (tagid, userid, type) values (12, 25, 0);
insert into users_tags (tagid, userid, type) values (12, 25, 1);
insert into users_tags (tagid, userid, type) values (10, 25, 1);
insert into users_tags (tagid, userid, type) values (2, 25, 1);
insert into users_tags (tagid, userid, type) values (12, 26, 0);
insert into users_tags (tagid, userid, type) values (25, 26, 0);
insert into users_tags (tagid, userid, type) values (2, 26, 0);
insert into users_tags (tagid, userid, type) values (30, 26, 1);
insert into users_tags (tagid, userid, type) values (28, 26, 1);
insert into users_tags (tagid, userid, type) values (22, 26, 1);
insert into users_tags (tagid, userid, type) values (9, 27, 0);
insert into users_tags (tagid, userid, type) values (20, 27, 0);
insert into users_tags (tagid, userid, type) values (12, 27, 0);
insert into users_tags (tagid, userid, type) values (6, 27, 1);
insert into users_tags (tagid, userid, type) values (22, 27, 1);
insert into users_tags (tagid, userid, type) values (7, 27, 1);
insert into users_tags (tagid, userid, type) values (15, 28, 0);
insert into users_tags (tagid, userid, type) values (17, 28, 0);
insert into users_tags (tagid, userid, type) values (19, 28, 0);
insert into users_tags (tagid, userid, type) values (4, 28, 1);
insert into users_tags (tagid, userid, type) values (13, 28, 1);
insert into users_tags (tagid, userid, type) values (7, 28, 1);
insert into users_tags (tagid, userid, type) values (13, 29, 0);
insert into users_tags (tagid, userid, type) values (26, 29, 0);
insert into users_tags (tagid, userid, type) values (3, 29, 0);
insert into users_tags (tagid, userid, type) values (7, 29, 1);
insert into users_tags (tagid, userid, type) values (21, 29, 1);
insert into users_tags (tagid, userid, type) values (14, 29, 1);
insert into users_tags (tagid, userid, type) values (23, 30, 0);
insert into users_tags (tagid, userid, type) values (16, 30, 0);
insert into users_tags (tagid, userid, type) values (2, 30, 0);
insert into users_tags (tagid, userid, type) values (19, 30, 1);
insert into users_tags (tagid, userid, type) values (17, 30, 1);
insert into users_tags (tagid, userid, type) values (9, 30, 1);
insert into users_tags (tagid, userid, type) values (3, 31, 0);
insert into users_tags (tagid, userid, type) values (5, 31, 0);
insert into users_tags (tagid, userid, type) values (11, 31, 0);
insert into users_tags (tagid, userid, type) values (6, 31, 1);
insert into users_tags (tagid, userid, type) values (11, 31, 1);
insert into users_tags (tagid, userid, type) values (21, 31, 1);
insert into users_tags (tagid, userid, type) values (29, 32, 0);
insert into users_tags (tagid, userid, type) values (4, 32, 0);
insert into users_tags (tagid, userid, type) values (17, 32, 0);
insert into users_tags (tagid, userid, type) values (30, 32, 1);
insert into users_tags (tagid, userid, type) values (12, 32, 1);
insert into users_tags (tagid, userid, type) values (10, 32, 1);
insert into users_tags (tagid, userid, type) values (13, 33, 0);
insert into users_tags (tagid, userid, type) values (15, 33, 0);
insert into users_tags (tagid, userid, type) values (4, 33, 0);
insert into users_tags (tagid, userid, type) values (19, 33, 1);
insert into users_tags (tagid, userid, type) values (28, 33, 1);
insert into users_tags (tagid, userid, type) values (25, 33, 1);
insert into users_tags (tagid, userid, type) values (23, 34, 0);
insert into users_tags (tagid, userid, type) values (24, 34, 0);
insert into users_tags (tagid, userid, type) values (29, 34, 0);
insert into users_tags (tagid, userid, type) values (22, 34, 1);
insert into users_tags (tagid, userid, type) values (26, 34, 1);
insert into users_tags (tagid, userid, type) values (4, 34, 1);
insert into users_tags (tagid, userid, type) values (17, 35, 0);
insert into users_tags (tagid, userid, type) values (7, 35, 0);
insert into users_tags (tagid, userid, type) values (19, 35, 0);
insert into users_tags (tagid, userid, type) values (25, 35, 1);
insert into users_tags (tagid, userid, type) values (27, 35, 1);
insert into users_tags (tagid, userid, type) values (13, 35, 1);
insert into users_tags (tagid, userid, type) values (23, 36, 0);
insert into users_tags (tagid, userid, type) values (18, 36, 0);
insert into users_tags (tagid, userid, type) values (23, 36, 0);
insert into users_tags (tagid, userid, type) values (23, 36, 1);
insert into users_tags (tagid, userid, type) values (15, 36, 1);
insert into users_tags (tagid, userid, type) values (24, 36, 1);
insert into users_tags (tagid, userid, type) values (15, 37, 0);
insert into users_tags (tagid, userid, type) values (24, 37, 0);
insert into users_tags (tagid, userid, type) values (18, 37, 0);
insert into users_tags (tagid, userid, type) values (18, 37, 1);
insert into users_tags (tagid, userid, type) values (23, 37, 1);
insert into users_tags (tagid, userid, type) values (26, 37, 1);
insert into users_tags (tagid, userid, type) values (16, 38, 0);
insert into users_tags (tagid, userid, type) values (29, 38, 0);
insert into users_tags (tagid, userid, type) values (12, 38, 0);
insert into users_tags (tagid, userid, type) values (29, 38, 1);
insert into users_tags (tagid, userid, type) values (1, 38, 1);
insert into users_tags (tagid, userid, type) values (4, 38, 1);
insert into users_tags (tagid, userid, type) values (3, 39, 0);
insert into users_tags (tagid, userid, type) values (6, 39, 0);
insert into users_tags (tagid, userid, type) values (17, 39, 0);
insert into users_tags (tagid, userid, type) values (8, 39, 1);
insert into users_tags (tagid, userid, type) values (6, 39, 1);
insert into users_tags (tagid, userid, type) values (18, 39, 1);
insert into users_tags (tagid, userid, type) values (24, 40, 0);
insert into users_tags (tagid, userid, type) values (9, 40, 0);
insert into users_tags (tagid, userid, type) values (28, 40, 0);
insert into users_tags (tagid, userid, type) values (7, 40, 1);
insert into users_tags (tagid, userid, type) values (20, 40, 1);
insert into users_tags (tagid, userid, type) values (12, 40, 1);
insert into users_tags (tagid, userid, type) values (13, 41, 0);
insert into users_tags (tagid, userid, type) values (10, 41, 0);
insert into users_tags (tagid, userid, type) values (12, 41, 0);
insert into users_tags (tagid, userid, type) values (10, 41, 1);
insert into users_tags (tagid, userid, type) values (19, 41, 1);
insert into users_tags (tagid, userid, type) values (13, 41, 1);
insert into users_tags (tagid, userid, type) values (13, 42, 0);
insert into users_tags (tagid, userid, type) values (10, 42, 0);
insert into users_tags (tagid, userid, type) values (30, 42, 0);
insert into users_tags (tagid, userid, type) values (27, 42, 1);
insert into users_tags (tagid, userid, type) values (30, 42, 1);
insert into users_tags (tagid, userid, type) values (10, 42, 1);
insert into users_tags (tagid, userid, type) values (9, 43, 0);
insert into users_tags (tagid, userid, type) values (20, 43, 0);
insert into users_tags (tagid, userid, type) values (11, 43, 0);
insert into users_tags (tagid, userid, type) values (17, 43, 1);
insert into users_tags (tagid, userid, type) values (8, 43, 1);
insert into users_tags (tagid, userid, type) values (25, 43, 1);
insert into users_tags (tagid, userid, type) values (20, 44, 0);
insert into users_tags (tagid, userid, type) values (25, 44, 0);
insert into users_tags (tagid, userid, type) values (3, 44, 0);
insert into users_tags (tagid, userid, type) values (10, 44, 1);
insert into users_tags (tagid, userid, type) values (12, 44, 1);
insert into users_tags (tagid, userid, type) values (30, 44, 1);
insert into users_tags (tagid, userid, type) values (20, 45, 0);
insert into users_tags (tagid, userid, type) values (18, 45, 0);
insert into users_tags (tagid, userid, type) values (9, 45, 0);
insert into users_tags (tagid, userid, type) values (24, 45, 1);
insert into users_tags (tagid, userid, type) values (5, 45, 1);
insert into users_tags (tagid, userid, type) values (27, 45, 1);
insert into users_tags (tagid, userid, type) values (22, 46, 0);
insert into users_tags (tagid, userid, type) values (2, 46, 0);
insert into users_tags (tagid, userid, type) values (5, 46, 0);
insert into users_tags (tagid, userid, type) values (25, 46, 1);
insert into users_tags (tagid, userid, type) values (5, 46, 1);
insert into users_tags (tagid, userid, type) values (12, 46, 1);
insert into users_tags (tagid, userid, type) values (17, 47, 0);
insert into users_tags (tagid, userid, type) values (2, 47, 0);
insert into users_tags (tagid, userid, type) values (11, 47, 0);
insert into users_tags (tagid, userid, type) values (22, 47, 1);
insert into users_tags (tagid, userid, type) values (2, 47, 1);
insert into users_tags (tagid, userid, type) values (30, 47, 1);
insert into users_tags (tagid, userid, type) values (10, 48, 0);
insert into users_tags (tagid, userid, type) values (6, 48, 0);
insert into users_tags (tagid, userid, type) values (22, 48, 0);
insert into users_tags (tagid, userid, type) values (9, 48, 1);
insert into users_tags (tagid, userid, type) values (11, 48, 1);
insert into users_tags (tagid, userid, type) values (1, 48, 1);
insert into users_tags (tagid, userid, type) values (15, 49, 0);
insert into users_tags (tagid, userid, type) values (19, 49, 0);
insert into users_tags (tagid, userid, type) values (8, 49, 0);
insert into users_tags (tagid, userid, type) values (3, 49, 1);
insert into users_tags (tagid, userid, type) values (30, 49, 1);
insert into users_tags (tagid, userid, type) values (23, 49, 1);
insert into users_tags (tagid, userid, type) values (1, 50, 0);
insert into users_tags (tagid, userid, type) values (2, 50, 0);
insert into users_tags (tagid, userid, type) values (3, 50, 0);
insert into users_tags (tagid, userid, type) values (21, 50, 1);
insert into users_tags (tagid, userid, type) values (22, 50, 1);
insert into users_tags (tagid, userid, type) values (15, 50, 1);
insert into users_tags (tagid, userid, type) values (15, 51, 0);
insert into users_tags (tagid, userid, type) values (21, 51, 0);
insert into users_tags (tagid, userid, type) values (22, 51, 0);
insert into users_tags (tagid, userid, type) values (1, 51, 1);
insert into users_tags (tagid, userid, type) values (2, 51, 1);
insert into users_tags (tagid, userid, type) values (3, 51, 1);
insert into users_tags (tagid, userid, type) values (12, 52, 0);
insert into users_tags (tagid, userid, type) values (14, 52, 0);
insert into users_tags (tagid, userid, type) values (9, 52, 0);
insert into users_tags (tagid, userid, type) values (12, 52, 1);
insert into users_tags (tagid, userid, type) values (6, 52, 1);
insert into users_tags (tagid, userid, type) values (9, 52, 1);
insert into users_tags (tagid, userid, type) values (1, 53, 0);
insert into users_tags (tagid, userid, type) values (26, 53, 0);
insert into users_tags (tagid, userid, type) values (11, 53, 0);
insert into users_tags (tagid, userid, type) values (27, 53, 1);
insert into users_tags (tagid, userid, type) values (2, 53, 1);
insert into users_tags (tagid, userid, type) values (13, 53, 1);
insert into users_tags (tagid, userid, type) values (15, 54, 0);
insert into users_tags (tagid, userid, type) values (21, 54, 0);
insert into users_tags (tagid, userid, type) values (22, 54, 0);
insert into users_tags (tagid, userid, type) values (1, 54, 1);
insert into users_tags (tagid, userid, type) values (2, 54, 1);
insert into users_tags (tagid, userid, type) values (3, 54, 1);
insert into users_tags (tagid, userid, type) values (30, 55, 0);
insert into users_tags (tagid, userid, type) values (12, 55, 0);
insert into users_tags (tagid, userid, type) values (24, 55, 0);
insert into users_tags (tagid, userid, type) values (20, 55, 1);
insert into users_tags (tagid, userid, type) values (13, 55, 1);
insert into users_tags (tagid, userid, type) values (2, 55, 1);
insert into users_tags (tagid, userid, type) values (29, 56, 0);
insert into users_tags (tagid, userid, type) values (12, 56, 0);
insert into users_tags (tagid, userid, type) values (3, 56, 0);
insert into users_tags (tagid, userid, type) values (2, 56, 1);
insert into users_tags (tagid, userid, type) values (19, 56, 1);
insert into users_tags (tagid, userid, type) values (22,56, 1);
insert into users_tags (tagid, userid, type) values (22, 57, 0);
insert into users_tags (tagid, userid, type) values (10, 57, 0);
insert into users_tags (tagid, userid, type) values (13, 57, 0);
insert into users_tags (tagid, userid, type) values (16, 57, 1);
insert into users_tags (tagid, userid, type) values (27, 57, 1);
insert into users_tags (tagid, userid, type) values (17, 57, 1);
insert into users_tags (tagid, userid, type) values (30, 58, 0);
insert into users_tags (tagid, userid, type) values (20, 58, 0);
insert into users_tags (tagid, userid, type) values (2, 58, 0);
insert into users_tags (tagid, userid, type) values (11, 58, 1);
insert into users_tags (tagid, userid, type) values (14, 58, 1);
insert into users_tags (tagid, userid, type) values (8, 58, 1);
insert into users_tags (tagid, userid, type) values (11, 59, 0);
insert into users_tags (tagid, userid, type) values (3, 59, 0);
insert into users_tags (tagid, userid, type) values (21, 59, 0);
insert into users_tags (tagid, userid, type) values (8, 59, 1);
insert into users_tags (tagid, userid, type) values (3, 59, 1);
insert into users_tags (tagid, userid, type) values (16, 59, 1);
insert into users_tags (tagid, userid, type) values (17, 60, 0);
insert into users_tags (tagid, userid, type) values (3, 60, 0);
insert into users_tags (tagid, userid, type) values (26, 60, 0);
insert into users_tags (tagid, userid, type) values (24, 60, 1);
insert into users_tags (tagid, userid, type) values (8, 60, 1);
insert into users_tags (tagid, userid, type) values (9, 60, 1);
insert into users_tags (tagid, userid, type) values (16, 61, 0);
insert into users_tags (tagid, userid, type) values (27, 61, 0);
insert into users_tags (tagid, userid, type) values (16, 61, 0);
insert into users_tags (tagid, userid, type) values (24, 61, 1);
insert into users_tags (tagid, userid, type) values (11, 61, 1);
insert into users_tags (tagid, userid, type) values (6, 61, 1);
insert into users_tags (tagid, userid, type) values (12, 62, 0);
insert into users_tags (tagid, userid, type) values (2, 62, 0);
insert into users_tags (tagid, userid, type) values (28, 62, 0);
insert into users_tags (tagid, userid, type) values (24, 62, 1);
insert into users_tags (tagid, userid, type) values (13, 62, 1);
insert into users_tags (tagid, userid, type) values (5, 62, 1);
insert into users_tags (tagid, userid, type) values (12, 63, 0);
insert into users_tags (tagid, userid, type) values (29, 63, 0);
insert into users_tags (tagid, userid, type) values (23, 63, 0);
insert into users_tags (tagid, userid, type) values (30, 63, 1);
insert into users_tags (tagid, userid, type) values (10, 63, 1);
insert into users_tags (tagid, userid, type) values (4, 63, 1);
insert into users_tags (tagid, userid, type) values (15, 64, 0);
insert into users_tags (tagid, userid, type) values (30,  64, 0);
insert into users_tags (tagid, userid, type) values (7,  64, 0);
insert into users_tags (tagid, userid, type) values (22,  64, 1);
insert into users_tags (tagid, userid, type) values (28,  64, 1);
insert into users_tags (tagid, userid, type) values (3,  64, 1);
insert into users_tags (tagid, userid, type) values (26, 65, 0);
insert into users_tags (tagid, userid, type) values (29, 65, 0);
insert into users_tags (tagid, userid, type) values (5, 65, 0);
insert into users_tags (tagid, userid, type) values (19, 65, 1);
insert into users_tags (tagid, userid, type) values (2, 65, 1);
insert into users_tags (tagid, userid, type) values (30, 65, 1);
insert into users_tags (tagid, userid, type) values (23, 66, 0);
insert into users_tags (tagid, userid, type) values (25, 66, 0);
insert into users_tags (tagid, userid, type) values (26, 66, 0);
insert into users_tags (tagid, userid, type) values (20, 66, 1);
insert into users_tags (tagid, userid, type) values (10, 66, 1);
insert into users_tags (tagid, userid, type) values (16, 66, 1);
insert into users_tags (tagid, userid, type) values (12, 67, 0);
insert into users_tags (tagid, userid, type) values (12, 67, 0);
insert into users_tags (tagid, userid, type) values (23, 67, 0);
insert into users_tags (tagid, userid, type) values (23, 67, 1);
insert into users_tags (tagid, userid, type) values (14, 67, 1);
insert into users_tags (tagid, userid, type) values (1, 67, 1);
insert into users_tags (tagid, userid, type) values (18, 68, 0);
insert into users_tags (tagid, userid, type) values (19, 68, 0);
insert into users_tags (tagid, userid, type) values (18, 68, 0);
insert into users_tags (tagid, userid, type) values (26, 68, 1);
insert into users_tags (tagid, userid, type) values (5, 68, 1);
insert into users_tags (tagid, userid, type) values (17, 68, 1);
insert into users_tags (tagid, userid, type) values (4, 69, 0);
insert into users_tags (tagid, userid, type) values (13, 69, 0);
insert into users_tags (tagid, userid, type) values (15, 69, 0);
insert into users_tags (tagid, userid, type) values (11, 69, 1);
insert into users_tags (tagid, userid, type) values (24, 69, 1);
insert into users_tags (tagid, userid, type) values (26, 69, 1);
insert into users_tags (tagid, userid, type) values (24, 70, 0);
insert into users_tags (tagid, userid, type) values (25, 70, 0);
insert into users_tags (tagid, userid, type) values (19, 70, 0);
insert into users_tags (tagid, userid, type) values (25, 70, 1);
insert into users_tags (tagid, userid, type) values (23, 70, 1);
insert into users_tags (tagid, userid, type) values (7, 70, 1);
insert into users_tags (tagid, userid, type) values (9, 71, 0);
insert into users_tags (tagid, userid, type) values (22, 71, 0);
insert into users_tags (tagid, userid, type) values (20, 71, 0);
insert into users_tags (tagid, userid, type) values (17, 71, 1);
insert into users_tags (tagid, userid, type) values (23, 71, 1);
insert into users_tags (tagid, userid, type) values (9, 71, 1);
insert into users_tags (tagid, userid, type) values (25, 72, 0);
insert into users_tags (tagid, userid, type) values (8, 72, 0);
insert into users_tags (tagid, userid, type) values (4, 72, 0);
insert into users_tags (tagid, userid, type) values (8, 72, 1);
insert into users_tags (tagid, userid, type) values (17, 72, 1);
insert into users_tags (tagid, userid, type) values (24, 72, 1);
insert into users_tags (tagid, userid, type) values (18, 73, 0);
insert into users_tags (tagid, userid, type) values (2, 73, 0);
insert into users_tags (tagid, userid, type) values (24, 73, 0);
insert into users_tags (tagid, userid, type) values (4, 73, 1);
insert into users_tags (tagid, userid, type) values (28, 73, 1);
insert into users_tags (tagid, userid, type) values (4, 73, 1);
insert into users_tags (tagid, userid, type) values (10, 74, 0);
insert into users_tags (tagid, userid, type) values (29, 74, 0);
insert into users_tags (tagid, userid, type) values (13, 74, 0);
insert into users_tags (tagid, userid, type) values (11, 74, 1);
insert into users_tags (tagid, userid, type) values (6, 74, 1);
insert into users_tags (tagid, userid, type) values (8, 74, 1);
insert into users_tags (tagid, userid, type) values (14, 75, 0);
insert into users_tags (tagid, userid, type) values (30, 75, 0);
insert into users_tags (tagid, userid, type) values (5, 75, 0);
insert into users_tags (tagid, userid, type) values (7, 75, 1);
insert into users_tags (tagid, userid, type) values (1, 75, 1);
insert into users_tags (tagid, userid, type) values (19, 75, 1);
insert into users_tags (tagid, userid, type) values (11, 76, 0);
insert into users_tags (tagid, userid, type) values (5, 76, 0);
insert into users_tags (tagid, userid, type) values (3, 76, 0);
insert into users_tags (tagid, userid, type) values (15, 76, 1);
insert into users_tags (tagid, userid, type) values (3, 76, 1);
insert into users_tags (tagid, userid, type) values (27, 76, 1);
insert into users_tags (tagid, userid, type) values (2, 77, 0);
insert into users_tags (tagid, userid, type) values (23, 77, 0);
insert into users_tags (tagid, userid, type) values (26, 77, 0);
insert into users_tags (tagid, userid, type) values (29, 77, 1);
insert into users_tags (tagid, userid, type) values (7, 77, 1);
insert into users_tags (tagid, userid, type) values (1, 77, 1);
insert into users_tags (tagid, userid, type) values (22, 78, 0);
insert into users_tags (tagid, userid, type) values (3, 78, 0);
insert into users_tags (tagid, userid, type) values (18, 78, 0);
insert into users_tags (tagid, userid, type) values (19, 78, 1);
insert into users_tags (tagid, userid, type) values (3, 78, 1);
insert into users_tags (tagid, userid, type) values (13, 78, 1);
insert into users_tags (tagid, userid, type) values (14, 79, 0);
insert into users_tags (tagid, userid, type) values (25, 79, 0);
insert into users_tags (tagid, userid, type) values (23, 79, 0);
insert into users_tags (tagid, userid, type) values (24, 79, 1);
insert into users_tags (tagid, userid, type) values (11, 79, 1);
insert into users_tags (tagid, userid, type) values (23, 79, 1);
insert into users_tags (tagid, userid, type) values (12, 80, 0);
insert into users_tags (tagid, userid, type) values (16, 80, 0);
insert into users_tags (tagid, userid, type) values (29, 80, 0);
insert into users_tags (tagid, userid, type) values (2, 80, 1);
insert into users_tags (tagid, userid, type) values (3, 80, 1);
insert into users_tags (tagid, userid, type) values (4, 80, 1);
insert into users_tags (tagid, userid, type) values (19, 81, 0);
insert into users_tags (tagid, userid, type) values (20, 81, 0);
insert into users_tags (tagid, userid, type) values (19, 81, 0);
insert into users_tags (tagid, userid, type) values (6, 81, 1);
insert into users_tags (tagid, userid, type) values (12, 81, 1);
insert into users_tags (tagid, userid, type) values (21, 81, 1);
insert into users_tags (tagid, userid, type) values (28, 82, 0);
insert into users_tags (tagid, userid, type) values (15, 82, 0);
insert into users_tags (tagid, userid, type) values (4, 82, 0);
insert into users_tags (tagid, userid, type) values (23, 82, 1);
insert into users_tags (tagid, userid, type) values (13, 82, 1);
insert into users_tags (tagid, userid, type) values (18, 82, 1);
insert into users_tags (tagid, userid, type) values (27, 83, 0);
insert into users_tags (tagid, userid, type) values (5, 83, 0);
insert into users_tags (tagid, userid, type) values (17, 83, 0);
insert into users_tags (tagid, userid, type) values (23, 83, 1);
insert into users_tags (tagid, userid, type) values (15, 83, 1);
insert into users_tags (tagid, userid, type) values (5, 83, 1);
insert into users_tags (tagid, userid, type) values (3, 84, 0);
insert into users_tags (tagid, userid, type) values (4, 84, 0);
insert into users_tags (tagid, userid, type) values (27, 84, 0);
insert into users_tags (tagid, userid, type) values (3, 84, 1);
insert into users_tags (tagid, userid, type) values (15, 84, 1);
insert into users_tags (tagid, userid, type) values (28, 84, 1);
insert into users_tags (tagid, userid, type) values (11, 85, 0);
insert into users_tags (tagid, userid, type) values (20, 85, 0);
insert into users_tags (tagid, userid, type) values (19, 85, 0);
insert into users_tags (tagid, userid, type) values (9, 85, 1);
insert into users_tags (tagid, userid, type) values (17, 85, 1);
insert into users_tags (tagid, userid, type) values (5, 85, 1);
insert into users_tags (tagid, userid, type) values (13, 86, 0);
insert into users_tags (tagid, userid, type) values (19, 86, 0);
insert into users_tags (tagid, userid, type) values (17, 86, 0);
insert into users_tags (tagid, userid, type) values (20, 86, 1);
insert into users_tags (tagid, userid, type) values (30, 86, 1);
insert into users_tags (tagid, userid, type) values (16, 86, 1);
insert into users_tags (tagid, userid, type) values (14, 87, 0);
insert into users_tags (tagid, userid, type) values (19, 87, 0);
insert into users_tags (tagid, userid, type) values (7, 87, 0);
insert into users_tags (tagid, userid, type) values (19, 87, 1);
insert into users_tags (tagid, userid, type) values (2, 87, 1);
insert into users_tags (tagid, userid, type) values (14, 87, 1);
insert into users_tags (tagid, userid, type) values (17, 88, 0);
insert into users_tags (tagid, userid, type) values (15, 88, 0);
insert into users_tags (tagid, userid, type) values (26, 88, 0);
insert into users_tags (tagid, userid, type) values (6, 88, 1);
insert into users_tags (tagid, userid, type) values (13, 88, 1);
insert into users_tags (tagid, userid, type) values (4, 88, 1);
insert into users_tags (tagid, userid, type) values (1, 89, 0);
insert into users_tags (tagid, userid, type) values (12, 89, 0);
insert into users_tags (tagid, userid, type) values (17, 89, 0);
insert into users_tags (tagid, userid, type) values (27, 89, 1);
insert into users_tags (tagid, userid, type) values (30, 89, 1);
insert into users_tags (tagid, userid, type) values (25, 89, 1);
insert into users_tags (tagid, userid, type) values (30, 90, 0);
insert into users_tags (tagid, userid, type) values (16, 90, 0);
insert into users_tags (tagid, userid, type) values (3, 90, 0);
insert into users_tags (tagid, userid, type) values (6, 90, 1);
insert into users_tags (tagid, userid, type) values (23, 90, 1);
insert into users_tags (tagid, userid, type) values (26, 90, 1);
insert into users_tags (tagid, userid, type) values (5, 91, 0);
insert into users_tags (tagid, userid, type) values (28, 91, 0);
insert into users_tags (tagid, userid, type) values (9, 91, 0);
insert into users_tags (tagid, userid, type) values (6, 91, 1);
insert into users_tags (tagid, userid, type) values (27, 91, 1);
insert into users_tags (tagid, userid, type) values (27, 91, 1);
insert into users_tags (tagid, userid, type) values (21, 92, 0);
insert into users_tags (tagid, userid, type) values (13, 92, 0);
insert into users_tags (tagid, userid, type) values (1, 92, 0);
insert into users_tags (tagid, userid, type) values (27, 92, 1);
insert into users_tags (tagid, userid, type) values (16, 92, 1);
insert into users_tags (tagid, userid, type) values (2, 92, 1);
insert into users_tags (tagid, userid, type) values (4, 93, 0);
insert into users_tags (tagid, userid, type) values (8, 93, 0);
insert into users_tags (tagid, userid, type) values (29, 93, 0);
insert into users_tags (tagid, userid, type) values (2, 93, 1);
insert into users_tags (tagid, userid, type) values (20, 93, 1);
insert into users_tags (tagid, userid, type) values (29, 93, 1);
insert into users_tags (tagid, userid, type) values (3, 94, 0);
insert into users_tags (tagid, userid, type) values (12, 94, 0);
insert into users_tags (tagid, userid, type) values (4, 94, 0);
insert into users_tags (tagid, userid, type) values (4, 94, 1);
insert into users_tags (tagid, userid, type) values (22, 94, 1);
insert into users_tags (tagid, userid, type) values (24, 94, 1);
insert into users_tags (tagid, userid, type) values (4, 95, 0);
insert into users_tags (tagid, userid, type) values (16, 95, 0);
insert into users_tags (tagid, userid, type) values (19, 95, 0);
insert into users_tags (tagid, userid, type) values (9, 95, 1);
insert into users_tags (tagid, userid, type) values (8, 95, 1);
insert into users_tags (tagid, userid, type) values (4, 95, 1);
insert into users_tags (tagid, userid, type) values (6, 96, 0);
insert into users_tags (tagid, userid, type) values (27, 96, 0);
insert into users_tags (tagid, userid, type) values (5, 96, 0);
insert into users_tags (tagid, userid, type) values (19, 96, 1);
insert into users_tags (tagid, userid, type) values (5, 96, 1);
insert into users_tags (tagid, userid, type) values (4, 96, 1);
insert into users_tags (tagid, userid, type) values (23, 97, 0);
insert into users_tags (tagid, userid, type) values (25, 97, 0);
insert into users_tags (tagid, userid, type) values (19, 97, 0);
insert into users_tags (tagid, userid, type) values (14, 97, 1);
insert into users_tags (tagid, userid, type) values (24, 97, 1);
insert into users_tags (tagid, userid, type) values (21, 97, 1);
insert into users_tags (tagid, userid, type) values (21, 98, 0);
insert into users_tags (tagid, userid, type) values (16, 98, 0);
insert into users_tags (tagid, userid, type) values (21, 98, 0);
insert into users_tags (tagid, userid, type) values (8, 98, 1);
insert into users_tags (tagid, userid, type) values (23, 98, 1);
insert into users_tags (tagid, userid, type) values (1, 98, 1);
insert into users_tags (tagid, userid, type) values (7, 99, 0);
insert into users_tags (tagid, userid, type) values (19, 99, 0);
insert into users_tags (tagid, userid, type) values (5, 99, 0);
insert into users_tags (tagid, userid, type) values (21, 99, 1);
insert into users_tags (tagid, userid, type) values (16, 99, 1);
insert into users_tags (tagid, userid, type) values (7, 99, 1);
insert into users_tags (tagid, userid, type) values (29, 100, 0);
insert into users_tags (tagid, userid, type) values (1, 100, 0);
insert into users_tags (tagid, userid, type) values (4, 100, 0);
insert into users_tags (tagid, userid, type) values (3, 100, 1);
insert into users_tags (tagid, userid, type) values (28, 100, 1);
insert into users_tags (tagid, userid, type) values (21, 100, 1);


insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/99.jpg', 1, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/66.jpg', 2, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/59.jpg', 3, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/21.jpg', 4, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/33.jpg', 5, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/60.jpg', 6, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/73.jpg', 7, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/82.jpg', 8, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/31.jpg', 9, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 10, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/23.jpg', 11, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/67.jpg', 12, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/20.jpg', 13, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/73.jpg', 14, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/56.jpg', 15, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/26.jpg', 16, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/14.jpg', 17, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/32.jpg', 18, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/30.jpg', 19, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/0.jpg', 20, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 21, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/64.jpg', 22, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/11.jpg', 23, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/99.jpg', 24, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/37.jpg', 25, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/65.jpg', 26, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/97.jpg', 27, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/63.jpg', 28, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/71.jpg', 29, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/19.jpg', 30, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/86.jpg', 31, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/91.jpg', 32, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/20.jpg', 33, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/83.jpg', 34, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/81.jpg', 35, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/4.jpg', 36, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/18.jpg', 37, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/86.jpg', 38, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/28.jpg', 39, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/41.jpg', 40, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/11.jpg', 41, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/73.jpg', 42, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/82.jpg', 43, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/66.jpg', 44, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/44.jpg', 45, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/57.jpg', 46, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/51.jpg', 47, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/27.jpg', 48, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/83.jpg', 49, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/96.jpg', 50, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/2.jpg', 51, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/5.jpg', 52, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/56.jpg', 53, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/18.jpg', 54, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/55.jpg', 55, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/45.jpg', 56, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/11.jpg', 57, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/61.jpg', 58, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/29.jpg', 59, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/59.jpg', 60, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/86.jpg', 61, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/59.jpg', 62, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/59.jpg', 63, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/60.jpg', 64, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 65, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/75.jpg', 66, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/24.jpg', 67, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/76.jpg', 68, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 69, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/36.jpg', 70, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/71.jpg', 71, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/88.jpg', 72, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/40.jpg', 73, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/65.jpg', 74, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/18.jpg', 75, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/22.jpg', 76, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/66.jpg', 77, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/7.jpg', 78, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/76.jpg', 79, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/44.jpg', 80, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/30.jpg', 81, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/73.jpg', 82, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/76.jpg', 83, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/57.jpg', 84, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/9.jpg', 85, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/25.jpg', 86, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/47.jpg' , 87, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/48.jpg', 88, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/77.jpg', 89, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/98.jpg', 90, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/71.jpg', 91, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 92, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/81.jpg', 93, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/92.jpg', 94, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/24.jpg' , 95, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/25.jpg', 96, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/6.jpg', 97, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/78.jpg', 98, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/women/95.jpg', 99, 1);
insert into photo (url, userid, primaryphoto) values ('https://randomuser.me/api/portraits/men/24.jpg', 100, 1);