insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('vpauncefoot0', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'vpauncefoot0@theguardian.com', 'Pauncefoot', 'Vail', 1996, 26005, 2, 4, 'Distributed didactic complexity', 0, 60, 10, 6, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('cdevaen1', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'cdevaen1@artisteer.com', 'de Vaen', 'Craggy', 1950, 54422, 1, 6, 'Vision-oriented national structure', 0, 60, 10, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('mshaves2', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'mshaves2@ocn.ne.jp', 'Shaves', 'Micheil', 1939, 49947, 3, 4, 'Configurable multi-tasking attitude', 0, 60, 10, 6, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('ksanthouse3', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'ksanthouse3@fema.gov', 'Santhouse', 'Kathryn', 1987, 26628, 1, 7, 'Visionary uniform firmware', 0, 50, 10, 5, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('vantoney4', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'vantoney4@google.com', 'Antoney', 'Valaree', 1983, 41875, 2, 5, 'Customizable object-oriented infrastructure', 0, 50, 10, 5, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('abrookson5', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'abrookson5@chronoengine.com', 'Brookson', 'Anthony', 1964, 56510, 2, 7, 'Innovative holistic moratorium', 0, 50, 10, 5, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('estonhewer6', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'estonhewer6@arizona.edu', 'Stonhewer', 'Eldredge', 1933, 45089, 2, 7, 'Reduced global hardware', 0, 10, 10, 1, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('kmorriss7', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'kmorriss7@sciencedaily.com', 'Morriss', 'Kristine', 1961, 84265, 1, 6, 'Quality-focused clear-thinking matrix', 0, 10, 10, 1, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('gbendin8', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'gbendin8@scribd.com', 'Bendin', 'Garald', 1959, 63620, 1, 6, 'Monitored multi-state solution', 0, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('wskentelbery9', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'wskentelbery9@seattletimes.com', 'Skentelbery', 'Willem', 1983, 94987, 2, 7, 'Secured stable capacity', 0, 10, 10, 1, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('bhindricha', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'bhindricha@wikispaces.com', 'Hindrich', 'Benedetta', 1998, 85749, 2, 6, 'Progressive multimedia definition', 0, 20, 10, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('dmathiasb', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'dmathiasb@google.co.uk', 'Mathias', 'Damien', 1961, 62323, 2, 5, 'Right-sized impactful algorithm', 0, 20, 10, 2, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('eplankec', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'eplankec@utexas.edu', 'Planke', 'Estelle', 1996, 99049, 2, 5, 'Automated 3rd generation benchmark', 0, 30, 10, 3, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('rbrasenerd', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'rbrasenerd@wordpress.com', 'Brasener', 'Roseanne', 1947, 77606, 2, 6, 'Team-oriented maximized contingency', 0, 30, 10, 3, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('kespiee', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'kespiee@twitpic.com', 'Espie', 'Kellie', 1976, 66720, 3, 6, 'Switchable fresh-thinking synergy', 0, 40, 10, 4, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('swillasf', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'swillasf@1688.com', 'Willas', 'Susana', 1986, 45343, 3, 7, 'Object-based system-worthy knowledge user', 0, 40, 10, 4, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('gvallisg', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'gvallisg@4shared.com', 'Vallis', 'Ginger', 1988, 65080, 3, 5, 'Assimilated needs-based hierarchy', 0, 100, 10, 10, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('athomasenh', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'athomasenh@w3.org', 'Thomasen', 'Ashia', 1965, 83246, 3, 5, 'Multi-layered mission-critical collaboration', 0, 100, 10, 10, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('pkealyi', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'pkealyi@google.co.jp', 'Kealy', 'Patrick', 1942, 93543, 3, 5, 'Enhanced object-oriented Graphical User Interface', 0, 90, 10, 9, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('rwatheyj', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'rwatheyj@live.com', 'Wathey', 'Reinold', 1994, 75066, 2, 5, 'Implemented user-facing parallelism', 0, 90, 10, 9, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('massandrik', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'massandrik@about.me', 'Assandri', 'Miranda', 1973, 47198, 3, 6, 'Operative dynamic capacity', 0, 70, 10, 7, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('ogodilingtonl', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'ogodilingtonl@fda.gov', 'Godilington', 'Odelia', 1986, 61293, 3, 6, 'User-friendly mobile firmware', 0, 70, 10, 7, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('esousterm', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'esousterm@yahoo.com', 'Souster', 'Eduino', 1990, 89261, 2, 6, 'Open-source multimedia Graphic Interface', 0, 80, 10, 8, false);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('rbaalhamn', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'rbaalhamn@goo.ne.jp', 'Baalham', 'Rory', 1978, 10853, 1, 5, 'Operative heuristic Graphic Interface', 0, 80, 10, 8, true);
insert into users (username, password, email, lastname, firstname, age, location, gender, preference, bio, powerRanking, totalAttractiveness, totalNumOfRatings, averageAttractiveness, signupcomplete) values ('dauldso', '6c12a3cd28b6e5730535c2d926e619137f30f5cc', 'dauldso@ustream.tv', 'Aulds', 'Dorie', 1940, 59045, 2, 7, 'Open-source attitude-oriented infrastructure', 0, 80, 10, 8, false);

insert into match (user1_id, user2_id) values (7, 25);
insert into match (user1_id, user2_id) values (6, 25);
insert into match (user1_id, user2_id) values (10, 22);
insert into match (user1_id, user2_id) values (8, 16);
insert into match (user1_id, user2_id) values (2, 25);
insert into match (user1_id, user2_id) values (3, 21);
insert into match (user1_id, user2_id) values (4, 23);
insert into match (user1_id, user2_id) values (1, 16);
insert into match (user1_id, user2_id) values (4, 14);
insert into match (user1_id, user2_id) values (7, 15);
insert into match (user1_id, user2_id) values (12, 16);
insert into match (user1_id, user2_id) values (13, 22);
insert into match (user1_id, user2_id) values (8, 19);
insert into match (user1_id, user2_id) values (12, 16);
insert into match (user1_id, user2_id) values (4, 25);

insert into outcomes (userid, matchid, decision) values (24, 2, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 4, 'approved');
insert into outcomes (userid, matchid, decision) values (8, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (1, 6, 'approved');
insert into outcomes (userid, matchid, decision) values (15, 10, 'approved');
insert into outcomes (userid, matchid, decision) values (12, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (2, 2, 'approved');
insert into outcomes (userid, matchid, decision) values (20, 11, 'approved');
insert into outcomes (userid, matchid, decision) values (7, 1, 'approved');
insert into outcomes (userid, matchid, decision) values (16, 8, 'approved');
insert into outcomes (userid, matchid, decision) values (8, 6, 'approved');
insert into outcomes (userid, matchid, decision) values (17, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (13, 9, 'approved');
insert into outcomes (userid, matchid, decision) values (1, 7, 'approved');
insert into outcomes (userid, matchid, decision) values (15, 14, 'approved');
insert into outcomes (userid, matchid, decision) values (17, 14, 'approved');
insert into outcomes (userid, matchid, decision) values (18, 12, 'approved');
insert into outcomes (userid, matchid, decision) values (4, 5, 'approved');
insert into outcomes (userid, matchid, decision) values (11, 4, 'approved');
insert into outcomes (userid, matchid, decision) values (11, 11, 'approved');
insert into outcomes (userid, matchid, decision) values (20, 10, 'approved');
insert into outcomes (userid, matchid, decision) values (22, 13, 'approved');
insert into outcomes (userid, matchid, decision) values (1, 10, 'approved');
insert into outcomes (userid, matchid, decision) values (17, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (25, 9, 'approved');
insert into outcomes (userid, matchid, decision) values (8, 2, 'approved');
insert into outcomes (userid, matchid, decision) values (15, 7, 'approved');
insert into outcomes (userid, matchid, decision) values (25, 5, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 14, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 12, 'approved');
insert into outcomes (userid, matchid, decision) values (20, 13, 'approved');
insert into outcomes (userid, matchid, decision) values (7, 15, 'approved');
insert into outcomes (userid, matchid, decision) values (5, 4, 'approved');
insert into outcomes (userid, matchid, decision) values (9, 13, 'rejected');
insert into outcomes (userid, matchid, decision) values (18, 10, 'rejected');
insert into outcomes (userid, matchid, decision) values (5, 4, 'rejected');
insert into outcomes (userid, matchid, decision) values (25, 5, 'rejected');
insert into outcomes (userid, matchid, decision) values (12, 12, 'rejected');
insert into outcomes (userid, matchid, decision) values (24, 13, 'rejected');
insert into outcomes (userid, matchid, decision) values (5, 14, 'rejected');
insert into outcomes (userid, matchid, decision) values (17, 11, 'rejected');
insert into outcomes (userid, matchid, decision) values (22, 14, 'rejected');
insert into outcomes (userid, matchid, decision) values (2, 8, 'rejected');
insert into outcomes (userid, matchid, decision) values (13, 7, 'rejected');
insert into outcomes (userid, matchid, decision) values (17, 6, 'rejected');
insert into outcomes (userid, matchid, decision) values (25, 13, 'rejected');
insert into outcomes (userid, matchid, decision) values (20, 14, 'rejected');
insert into outcomes (userid, matchid, decision) values (19, 5, 'rejected');
insert into outcomes (userid, matchid, decision) values (10, 15, 'rejected');

insert into stagetwo (matchid) values (12);
insert into stagetwo (matchid) values (8);
insert into stagetwo (matchid) values (12);
insert into stagetwo (matchid) values (6);
insert into stagetwo (matchid) values (13);
insert into stagetwo (matchid) values (9);
insert into stagetwo (matchid) values (6);
insert into stagetwo (matchid) values (1);
insert into stagetwo (matchid) values (8);
insert into stagetwo (matchid) values (1);

insert into tags (tag) values ('happy');
insert into tags (tag) values ('sad');
insert into tags (tag) values ('chill');

insert into users_tags (tagid, userid, type) values (2, 1, 0);
insert into users_tags (tagid, userid, type) values (3, 1, 0);
insert into users_tags (tagid, userid, type) values (1, 1, 0);
insert into users_tags (tagid, userid, type) values (1, 1, 1);
insert into users_tags (tagid, userid, type) values (2, 1, 1);
insert into users_tags (tagid, userid, type) values (3, 1, 1);

insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 1, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 2, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 3, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 4, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 5, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 6, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 7, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 8, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 9, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 10, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 11, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 12, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 13, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 14, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 15, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 16, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 17, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 18, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 19, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 20, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 21, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 22, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 23, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 24, 1);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 25, 1);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 1, 0);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 1, 0);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 1, 0);
insert into photo (url, userid, primaryphoto) values ('http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg', 2, 0);
insert into photo (url, userid, primaryphoto) values ('http://quikandslow.com/wp-content/uploads/tom-from-myspace-lg.jpg', 2, 0);
