insert into tags (tag) values ('Social Butterfly');
insert into tags (tag) values ('Ambitious');
insert into tags (tag) values ('Confident');
insert into tags (tag) values ('Party Animal');
insert into tags(tag) values ('Problem Solver');
insert into tags(tag) values ('Einstein');
insert into tags(tag) values ('Bookworm');
insert into tags(tag) values ('Analytical');
insert into tags(tag) values ('Puzzle Solver');
insert into tags(tag) values ('Artsy Fartsy');
insert into tags(tag) values ('Photographer');
insert into tags(tag) values ('Music Lover');
insert into tags(tag) values ('Patron of the Arts');
insert into tags(tag) values ('Trend Setter');
insert into tags(tag) values ('Shy');
insert into tags(tag) values ('Wallflower');
insert into tags(tag) values ('Gentle Giant');
insert into tags(tag) values ('Awkward Turtle');
insert into tags(tag) values ('Adventurous');
insert into tags(tag) values ('World Traveler');
insert into tags(tag) values ('Health Nut');
insert into tags(tag) values ('Athletic');
insert into tags(tag) values ('Homebody');
insert into tags(tag) values ('Nerdy');
insert into tags(tag) values ('Stoner');
insert into tags(tag) values ('Binge Watcher');
insert into tags(tag) values ('Wine Connoisseur');
insert into tags(tag) values ('Early Bird');
insert into tags(tag) values ('Night Owl');
insert into tags(tag) values ('Foodie');