export default [
    "Neat Freak",
    "Hardcore Gamer",
    "Book Worm",
    "Health Nut",
    "Patron of the Arts",
    "Sport Enthusist",
    "Party ANIMAL",
    "Stoner",
    "Cats!!!",
    "Dogs!!!",
    "Dogs || Cats",
    "Theater Kid",
    "Couch Potato",
    "Outdoorsy",
    "Socially Conscious",
    "Raver",
    "Religious",
    "Agnostic",
    "Atheist",
    "Conservative",
    "Liberal",
    "Dominant",
    "Creative",
    "Analytical",
    "Loyal",
    "Thoughtful",
    "Charitable",
    "Outcast",
    "Edgy",
    "Outgoing",
    "Adventerous",
    "Shy",
    "Chill"
]